version: 0.1.{build}
image: Visual Studio 2019


environment:
  matrix:
  - PlatformToolset: v142

platform:
    - x64
    - Win32
    - arm64

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="arm64" set archi=amd64_arm64
    - if "%platform%"=="arm64" set platform_input=arm64

    - if "%PlatformToolset%"=="v142" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\project\
    - msbuild NppDocShare.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-


        Push-AppveyorArtifact "build\$env:PLATFORM\$env:CONFIGURATION\NppDocShare.dll" -FileName NppDocShare.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v142") {
            $ZipFileName = "NppDocShare_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\build\$env:PLATFORM_INPUT\$env:CONFIGURATION\*.dll"
        }

artifacts:
  - path: NppDocShare_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: PhNXrhw03Z0rJZssX/UYyoIofw669wU1GBy/hGq+WJPCXd7mbxDu6Il32Rx0LBH6
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v142
        configuration: Release
